name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: LouisBrunner/checks-action@v2.0.0
        name: Rewrite summary
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 'Integration tests'
          status: completed
          conclusion: success
          sha: 'd6302d394f614a50c07ba8a8d0a51ce1d9a612f7'
          output: |
            {"summary":"Pending..."}

      - name: Prepare Integration test
        run: |
          #!/bin/bash
          content='- build_args:
              BACKEND_URL: https://example.com
            flavor: my-flavour-1
            image_repo: my-org/my-repo
            image_tag: v1.1.0-pre
            image_type: snapshots
            manifest: {}
            registries: my-acr.azurecr.io
            repository: service/my-org/my-repo
            version: v1.1.0-pre
          - build_args:
              BACKEND_URL: https://example.com
            flavor: my-flavour-4
            image_repo: my-org/my-repo
            image_tag: v1.1.0-pre
            image_type: snapshots
            manifest: {}
            registries: my-acr.azurecr.io
            repository: service/my-org/my-repo
            version: v1.1.0-pre'
            
            echo "$content" > /tmp/build_images_results.yaml

      - name: Test Local Action - Set Pending
        id: test-action-pending
        uses: ./
        with:
          status: in_progress
          token: ${{ secrets.GITHUB_TOKEN }}
          summary_path: /tmp/build_images_results.yaml
          check_run_name: 'Integration tests'
          ref: 'd6302d394f614a50c07ba8a8d0a51ce1d9a612f7'
          op: 'init-check-run'

      - name: Test Local Action - Set Success
        id: test-action-success
        uses: ./
        with:
          conclusion: 'success'
          token: ${{ secrets.GITHUB_TOKEN }}
          summary_path: '/tmp/build_images_results.yaml'
          check_run_name: 'Integration tests'
          ref: 'd6302d394f614a50c07ba8a8d0a51ce1d9a612f7'
          op: 'complete-check-run'

      - name: Test Local Action - Set Success
        id: test-action-get
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_run_name: 'Integration tests'
          ref: 'd6302d394f614a50c07ba8a8d0a51ce1d9a612f7'
          op: 'get-last-summary'
